// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Any struct {
	_tab flatbuffers.Table
}

func GetRootAsAny(buf []byte, offset flatbuffers.UOffsetT) *Any {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Any{}
	x.Init(buf, n+offset)
	return x
}

func FinishAnyBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAny(buf []byte, offset flatbuffers.UOffsetT) *Any {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Any{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAnyBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Any) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Any) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Any) ValType() AnyValue {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return AnyValue(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Any) MutateValType(n AnyValue) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *Any) Val(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func AnyStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AnyAddValType(builder *flatbuffers.Builder, valType AnyValue) {
	builder.PrependByteSlot(0, byte(valType), 0)
}
func AnyAddVal(builder *flatbuffers.Builder, val flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(val), 0)
}
func AnyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
