// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type AnyValue byte

const (
	AnyValueNONE        AnyValue = 0
	AnyValueBool        AnyValue = 1
	AnyValueNum         AnyValue = 2
	AnyValueInt         AnyValue = 3
	AnyValueStr         AnyValue = 4
	AnyValueErr         AnyValue = 5
	AnyValueAsyncHandle AnyValue = 6
	AnyValueNil         AnyValue = 7
	AnyValueGrid        AnyValue = 8
	AnyValueNumGrid     AnyValue = 9
	AnyValueRange       AnyValue = 10
	AnyValueRefCache    AnyValue = 11
)

var EnumNamesAnyValue = map[AnyValue]string{
	AnyValueNONE:        "NONE",
	AnyValueBool:        "Bool",
	AnyValueNum:         "Num",
	AnyValueInt:         "Int",
	AnyValueStr:         "Str",
	AnyValueErr:         "Err",
	AnyValueAsyncHandle: "AsyncHandle",
	AnyValueNil:         "Nil",
	AnyValueGrid:        "Grid",
	AnyValueNumGrid:     "NumGrid",
	AnyValueRange:       "Range",
	AnyValueRefCache:    "RefCache",
}

var EnumValuesAnyValue = map[string]AnyValue{
	"NONE":        AnyValueNONE,
	"Bool":        AnyValueBool,
	"Num":         AnyValueNum,
	"Int":         AnyValueInt,
	"Str":         AnyValueStr,
	"Err":         AnyValueErr,
	"AsyncHandle": AnyValueAsyncHandle,
	"Nil":         AnyValueNil,
	"Grid":        AnyValueGrid,
	"NumGrid":     AnyValueNumGrid,
	"Range":       AnyValueRange,
	"RefCache":    AnyValueRefCache,
}

func (v AnyValue) String() string {
	if s, ok := EnumNamesAnyValue[v]; ok {
		return s
	}
	return "AnyValue(" + strconv.FormatInt(int64(v), 10) + ")"
}
