// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AsyncResult struct {
	_tab flatbuffers.Table
}

func GetRootAsAsyncResult(buf []byte, offset flatbuffers.UOffsetT) *AsyncResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AsyncResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishAsyncResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAsyncResult(buf []byte, offset flatbuffers.UOffsetT) *AsyncResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AsyncResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAsyncResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AsyncResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AsyncResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AsyncResult) Handle() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AsyncResult) MutateHandle(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *AsyncResult) Result(obj *Any) *Any {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Any)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *AsyncResult) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AsyncResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func AsyncResultAddHandle(builder *flatbuffers.Builder, handle uint64) {
	builder.PrependUint64Slot(0, handle, 0)
}
func AsyncResultAddResult(builder *flatbuffers.Builder, result flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(result), 0)
}
func AsyncResultAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(error), 0)
}
func AsyncResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
