// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BatchRtdUpdate struct {
	_tab flatbuffers.Table
}

func GetRootAsBatchRtdUpdate(buf []byte, offset flatbuffers.UOffsetT) *BatchRtdUpdate {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BatchRtdUpdate{}
	x.Init(buf, n+offset)
	return x
}

func FinishBatchRtdUpdateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBatchRtdUpdate(buf []byte, offset flatbuffers.UOffsetT) *BatchRtdUpdate {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BatchRtdUpdate{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBatchRtdUpdateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BatchRtdUpdate) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BatchRtdUpdate) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BatchRtdUpdate) Updates(obj *RtdUpdate, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *BatchRtdUpdate) UpdatesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func BatchRtdUpdateStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func BatchRtdUpdateAddUpdates(builder *flatbuffers.Builder, updates flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(updates), 0)
}
func BatchRtdUpdateStartUpdatesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BatchRtdUpdateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
