// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CalculationEndedResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsCalculationEndedResponse(buf []byte, offset flatbuffers.UOffsetT) *CalculationEndedResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CalculationEndedResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishCalculationEndedResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCalculationEndedResponse(buf []byte, offset flatbuffers.UOffsetT) *CalculationEndedResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CalculationEndedResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCalculationEndedResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CalculationEndedResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CalculationEndedResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CalculationEndedResponse) Commands(obj *CommandWrapper, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *CalculationEndedResponse) CommandsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func CalculationEndedResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CalculationEndedResponseAddCommands(builder *flatbuffers.Builder, commands flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(commands), 0)
}
func CalculationEndedResponseStartCommandsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func CalculationEndedResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
