// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type Command byte

const (
	CommandNONE          Command = 0
	CommandSetCommand    Command = 1
	CommandFormatCommand Command = 2
)

var EnumNamesCommand = map[Command]string{
	CommandNONE:          "NONE",
	CommandSetCommand:    "SetCommand",
	CommandFormatCommand: "FormatCommand",
}

var EnumValuesCommand = map[string]Command{
	"NONE":          CommandNONE,
	"SetCommand":    CommandSetCommand,
	"FormatCommand": CommandFormatCommand,
}

func (v Command) String() string {
	if s, ok := EnumNamesCommand[v]; ok {
		return s
	}
	return "Command(" + strconv.FormatInt(int64(v), 10) + ")"
}
