// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CommandWrapper struct {
	_tab flatbuffers.Table
}

func GetRootAsCommandWrapper(buf []byte, offset flatbuffers.UOffsetT) *CommandWrapper {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CommandWrapper{}
	x.Init(buf, n+offset)
	return x
}

func FinishCommandWrapperBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCommandWrapper(buf []byte, offset flatbuffers.UOffsetT) *CommandWrapper {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CommandWrapper{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCommandWrapperBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CommandWrapper) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CommandWrapper) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CommandWrapper) CmdType() Command {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return Command(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *CommandWrapper) MutateCmdType(n Command) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *CommandWrapper) Cmd(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func CommandWrapperStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CommandWrapperAddCmdType(builder *flatbuffers.Builder, cmdType Command) {
	builder.PrependByteSlot(0, byte(cmdType), 0)
}
func CommandWrapperAddCmd(builder *flatbuffers.Builder, cmd flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(cmd), 0)
}
func CommandWrapperEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
