// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Err struct {
	_tab flatbuffers.Table
}

func GetRootAsErr(buf []byte, offset flatbuffers.UOffsetT) *Err {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Err{}
	x.Init(buf, n+offset)
	return x
}

func FinishErrBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsErr(buf []byte, offset flatbuffers.UOffsetT) *Err {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Err{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedErrBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Err) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Err) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Err) Val() XlError {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return XlError(rcv._tab.GetInt16(o + rcv._tab.Pos))
	}
	return 2000
}

func (rcv *Err) MutateVal(n XlError) bool {
	return rcv._tab.MutateInt16Slot(4, int16(n))
}

func ErrStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ErrAddVal(builder *flatbuffers.Builder, val XlError) {
	builder.PrependInt16Slot(0, int16(val), 2000)
}
func ErrEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
