// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Grid struct {
	_tab flatbuffers.Table
}

func GetRootAsGrid(buf []byte, offset flatbuffers.UOffsetT) *Grid {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Grid{}
	x.Init(buf, n+offset)
	return x
}

func FinishGridBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGrid(buf []byte, offset flatbuffers.UOffsetT) *Grid {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Grid{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGridBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Grid) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Grid) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Grid) Rows() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Grid) MutateRows(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *Grid) Cols() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Grid) MutateCols(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *Grid) Data(obj *Scalar, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Grid) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func GridStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func GridAddRows(builder *flatbuffers.Builder, rows int32) {
	builder.PrependInt32Slot(0, rows, 0)
}
func GridAddCols(builder *flatbuffers.Builder, cols int32) {
	builder.PrependInt32Slot(1, cols, 0)
}
func GridAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(data), 0)
}
func GridStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GridEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
