// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Nil struct {
	_tab flatbuffers.Table
}

func GetRootAsNil(buf []byte, offset flatbuffers.UOffsetT) *Nil {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Nil{}
	x.Init(buf, n+offset)
	return x
}

func FinishNilBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsNil(buf []byte, offset flatbuffers.UOffsetT) *Nil {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Nil{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNilBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Nil) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Nil) Table() flatbuffers.Table {
	return rcv._tab
}

func NilStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func NilEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
