// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Num struct {
	_tab flatbuffers.Table
}

func GetRootAsNum(buf []byte, offset flatbuffers.UOffsetT) *Num {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Num{}
	x.Init(buf, n+offset)
	return x
}

func FinishNumBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsNum(buf []byte, offset flatbuffers.UOffsetT) *Num {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Num{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNumBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Num) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Num) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Num) Val() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Num) MutateVal(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func NumStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func NumAddVal(builder *flatbuffers.Builder, val float64) {
	builder.PrependFloat64Slot(0, val, 0.0)
}
func NumEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
