// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NumGrid struct {
	_tab flatbuffers.Table
}

func GetRootAsNumGrid(buf []byte, offset flatbuffers.UOffsetT) *NumGrid {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NumGrid{}
	x.Init(buf, n+offset)
	return x
}

func FinishNumGridBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsNumGrid(buf []byte, offset flatbuffers.UOffsetT) *NumGrid {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &NumGrid{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNumGridBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *NumGrid) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NumGrid) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NumGrid) Rows() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *NumGrid) MutateRows(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *NumGrid) Cols() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *NumGrid) MutateCols(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *NumGrid) Data(j int) float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *NumGrid) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *NumGrid) MutateData(j int, n float64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func NumGridStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func NumGridAddRows(builder *flatbuffers.Builder, rows int32) {
	builder.PrependInt32Slot(0, rows, 0)
}
func NumGridAddCols(builder *flatbuffers.Builder, cols int32) {
	builder.PrependInt32Slot(1, cols, 0)
}
func NumGridAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(data), 0)
}
func NumGridStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func NumGridEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
