// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Rect struct {
	_tab flatbuffers.Struct
}

func (rcv *Rect) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Rect) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Rect) RowFirst() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Rect) MutateRowFirst(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *Rect) RowLast() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *Rect) MutateRowLast(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *Rect) ColFirst() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *Rect) MutateColFirst(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *Rect) ColLast() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(12))
}
func (rcv *Rect) MutateColLast(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(12), n)
}

func CreateRect(builder *flatbuffers.Builder, rowFirst int32, rowLast int32, colFirst int32, colLast int32) flatbuffers.UOffsetT {
	builder.Prep(4, 16)
	builder.PrependInt32(colLast)
	builder.PrependInt32(colFirst)
	builder.PrependInt32(rowLast)
	builder.PrependInt32(rowFirst)
	return builder.Offset()
}
