// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RefCache struct {
	_tab flatbuffers.Table
}

func GetRootAsRefCache(buf []byte, offset flatbuffers.UOffsetT) *RefCache {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RefCache{}
	x.Init(buf, n+offset)
	return x
}

func FinishRefCacheBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRefCache(buf []byte, offset flatbuffers.UOffsetT) *RefCache {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RefCache{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRefCacheBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RefCache) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RefCache) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RefCache) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RefCacheStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RefCacheAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func RefCacheEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
