// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RtdConnectResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsRtdConnectResponse(buf []byte, offset flatbuffers.UOffsetT) *RtdConnectResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RtdConnectResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishRtdConnectResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRtdConnectResponse(buf []byte, offset flatbuffers.UOffsetT) *RtdConnectResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RtdConnectResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRtdConnectResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RtdConnectResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RtdConnectResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RtdConnectResponse) Val(obj *Any) *Any {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Any)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func RtdConnectResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RtdConnectResponseAddVal(builder *flatbuffers.Builder, val flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(val), 0)
}
func RtdConnectResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
