// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RtdConnectRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsRtdConnectRequest(buf []byte, offset flatbuffers.UOffsetT) *RtdConnectRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RtdConnectRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishRtdConnectRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRtdConnectRequest(buf []byte, offset flatbuffers.UOffsetT) *RtdConnectRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RtdConnectRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRtdConnectRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RtdConnectRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RtdConnectRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RtdConnectRequest) TopicId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RtdConnectRequest) MutateTopicId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *RtdConnectRequest) Strings(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *RtdConnectRequest) StringsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *RtdConnectRequest) NewValues() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *RtdConnectRequest) MutateNewValues(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func RtdConnectRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func RtdConnectRequestAddTopicId(builder *flatbuffers.Builder, topicId int32) {
	builder.PrependInt32Slot(0, topicId, 0)
}
func RtdConnectRequestAddStrings(builder *flatbuffers.Builder, strings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(strings), 0)
}
func RtdConnectRequestStartStringsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func RtdConnectRequestAddNewValues(builder *flatbuffers.Builder, newValues bool) {
	builder.PrependBoolSlot(2, newValues, false)
}
func RtdConnectRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
