// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RtdDisconnectRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsRtdDisconnectRequest(buf []byte, offset flatbuffers.UOffsetT) *RtdDisconnectRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RtdDisconnectRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishRtdDisconnectRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRtdDisconnectRequest(buf []byte, offset flatbuffers.UOffsetT) *RtdDisconnectRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RtdDisconnectRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRtdDisconnectRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RtdDisconnectRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RtdDisconnectRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RtdDisconnectRequest) TopicId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RtdDisconnectRequest) MutateTopicId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func RtdDisconnectRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RtdDisconnectRequestAddTopicId(builder *flatbuffers.Builder, topicId int32) {
	builder.PrependInt32Slot(0, topicId, 0)
}
func RtdDisconnectRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
