// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RtdUpdate struct {
	_tab flatbuffers.Table
}

func GetRootAsRtdUpdate(buf []byte, offset flatbuffers.UOffsetT) *RtdUpdate {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RtdUpdate{}
	x.Init(buf, n+offset)
	return x
}

func FinishRtdUpdateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRtdUpdate(buf []byte, offset flatbuffers.UOffsetT) *RtdUpdate {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RtdUpdate{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRtdUpdateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RtdUpdate) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RtdUpdate) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RtdUpdate) TopicId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RtdUpdate) MutateTopicId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *RtdUpdate) Val(obj *Any) *Any {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Any)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func RtdUpdateStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RtdUpdateAddTopicId(builder *flatbuffers.Builder, topicId int32) {
	builder.PrependInt32Slot(0, topicId, 0)
}
func RtdUpdateAddVal(builder *flatbuffers.Builder, val flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(val), 0)
}
func RtdUpdateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
