// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type ScalarValue byte

const (
	ScalarValueNONE        ScalarValue = 0
	ScalarValueBool        ScalarValue = 1
	ScalarValueNum         ScalarValue = 2
	ScalarValueInt         ScalarValue = 3
	ScalarValueStr         ScalarValue = 4
	ScalarValueErr         ScalarValue = 5
	ScalarValueAsyncHandle ScalarValue = 6
	ScalarValueNil         ScalarValue = 7
)

var EnumNamesScalarValue = map[ScalarValue]string{
	ScalarValueNONE:        "NONE",
	ScalarValueBool:        "Bool",
	ScalarValueNum:         "Num",
	ScalarValueInt:         "Int",
	ScalarValueStr:         "Str",
	ScalarValueErr:         "Err",
	ScalarValueAsyncHandle: "AsyncHandle",
	ScalarValueNil:         "Nil",
}

var EnumValuesScalarValue = map[string]ScalarValue{
	"NONE":        ScalarValueNONE,
	"Bool":        ScalarValueBool,
	"Num":         ScalarValueNum,
	"Int":         ScalarValueInt,
	"Str":         ScalarValueStr,
	"Err":         ScalarValueErr,
	"AsyncHandle": ScalarValueAsyncHandle,
	"Nil":         ScalarValueNil,
}

func (v ScalarValue) String() string {
	if s, ok := EnumNamesScalarValue[v]; ok {
		return s
	}
	return "ScalarValue(" + strconv.FormatInt(int64(v), 10) + ")"
}
