// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Scalar struct {
	_tab flatbuffers.Table
}

func GetRootAsScalar(buf []byte, offset flatbuffers.UOffsetT) *Scalar {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Scalar{}
	x.Init(buf, n+offset)
	return x
}

func FinishScalarBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsScalar(buf []byte, offset flatbuffers.UOffsetT) *Scalar {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Scalar{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedScalarBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Scalar) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Scalar) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Scalar) ValType() ScalarValue {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return ScalarValue(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Scalar) MutateValType(n ScalarValue) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *Scalar) Val(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func ScalarStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ScalarAddValType(builder *flatbuffers.Builder, valType ScalarValue) {
	builder.PrependByteSlot(0, byte(valType), 0)
}
func ScalarAddVal(builder *flatbuffers.Builder, val flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(val), 0)
}
func ScalarEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
