// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SetRefCacheRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSetRefCacheRequest(buf []byte, offset flatbuffers.UOffsetT) *SetRefCacheRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SetRefCacheRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSetRefCacheRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSetRefCacheRequest(buf []byte, offset flatbuffers.UOffsetT) *SetRefCacheRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SetRefCacheRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSetRefCacheRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SetRefCacheRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SetRefCacheRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SetRefCacheRequest) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SetRefCacheRequest) Val(obj *Any) *Any {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Any)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SetRefCacheRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SetRefCacheRequestAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func SetRefCacheRequestAddVal(builder *flatbuffers.Builder, val flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(val), 0)
}
func SetRefCacheRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
