// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type XlError int16

const (
	XlErrorNull        XlError = 2000
	XlErrorDiv0        XlError = 2007
	XlErrorValue       XlError = 2015
	XlErrorRef         XlError = 2023
	XlErrorName        XlError = 2029
	XlErrorNum         XlError = 2036
	XlErrorNA          XlError = 2042
	XlErrorGettingData XlError = 2043
	XlErrorSpill       XlError = 2045
	XlErrorConnect     XlError = 2046
	XlErrorBlocked     XlError = 2047
	XlErrorUnknown     XlError = 2048
	XlErrorField       XlError = 2049
	XlErrorCalc        XlError = 2050
)

var EnumNamesXlError = map[XlError]string{
	XlErrorNull:        "Null",
	XlErrorDiv0:        "Div0",
	XlErrorValue:       "Value",
	XlErrorRef:         "Ref",
	XlErrorName:        "Name",
	XlErrorNum:         "Num",
	XlErrorNA:          "NA",
	XlErrorGettingData: "GettingData",
	XlErrorSpill:       "Spill",
	XlErrorConnect:     "Connect",
	XlErrorBlocked:     "Blocked",
	XlErrorUnknown:     "Unknown",
	XlErrorField:       "Field",
	XlErrorCalc:        "Calc",
}

var EnumValuesXlError = map[string]XlError{
	"Null":        XlErrorNull,
	"Div0":        XlErrorDiv0,
	"Value":       XlErrorValue,
	"Ref":         XlErrorRef,
	"Name":        XlErrorName,
	"Num":         XlErrorNum,
	"NA":          XlErrorNA,
	"GettingData": XlErrorGettingData,
	"Spill":       XlErrorSpill,
	"Connect":     XlErrorConnect,
	"Blocked":     XlErrorBlocked,
	"Unknown":     XlErrorUnknown,
	"Field":       XlErrorField,
	"Calc":        XlErrorCalc,
}

func (v XlError) String() string {
	if s, ok := EnumNamesXlError[v]; ok {
		return s
	}
	return "XlError(" + strconv.FormatInt(int64(v), 10) + ")"
}
