package cmd

import (
	"os/exec"
	"strconv"
	"strings"
	"testing"

	"github.com/xll-gen/xll-gen/version"
)

// TestVersionConstIsNotBehindTheNewestTag guards AGENTS §18.2 item 7: the
// version const is stamped into the "Code generated by xll-gen <ver>." banner of
// every generated file, so a stale const hands every downstream project false
// provenance.
//
// Why this test exists at all: the golden suite injects goldenVersion =
// "golden" (internal/generator/golden_test.go) precisely so goldens do not churn
// when the const is bumped. That is right for the goldens and it also means a
// forgotten bump breaks nothing — which is how v0.8.39 shipped with the const
// still reading v0.8.38.
//
// This is a BACKSTOP, not the mechanism. It cannot know the version an
// in-progress release intends, so it only asserts the weaker invariant: the
// const must never be BEHIND the newest tag. Being ahead is normal and expected
// — the release commit bumps the const before the tag exists.
func TestVersionConstIsNotBehindTheNewestTag(t *testing.T) {
	newest, err := newestSemverTag()
	if err != nil {
		t.Skipf("no usable git tag information (%v) — this backstop only runs in a git checkout", err)
	}

	got, ok := parseSemver(version.Version)
	if !ok {
		t.Fatalf("version.Version = %q is not a vMAJOR.MINOR.PATCH string", version.Version)
	}

	if less(got, newest) {
		t.Fatalf("version.Version = %q is BEHIND the newest tag %q.\n"+
			"The const is stamped into every generated file's banner, so regenerating now would\n"+
			"claim a generator that did not produce the output. Bump version/version.go to the\n"+
			"version this release will be tagged as (AGENTS §18.2 item 7).",
			version.Version, formatSemver(newest))
	}
}

type semver struct{ major, minor, patch int }

func newestSemverTag() (semver, error) {
	// --sort is applied by git itself so we do not reimplement ordering here.
	out, err := exec.Command("git", "tag", "--list", "v*", "--sort=-v:refname").Output()
	if err != nil {
		return semver{}, err
	}
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		if v, ok := parseSemver(strings.TrimSpace(line)); ok {
			return v, nil
		}
	}
	return semver{}, errNoTags
}

var errNoTags = errNoTagsType{}

type errNoTagsType struct{}

func (errNoTagsType) Error() string { return "no v* tags parse as semver" }

func parseSemver(s string) (semver, bool) {
	s = strings.TrimPrefix(strings.TrimSpace(s), "v")
	// Reject pre-release/build suffixes rather than guessing their ordering.
	parts := strings.Split(s, ".")
	if len(parts) != 3 {
		return semver{}, false
	}
	var v semver
	for i, dst := range []*int{&v.major, &v.minor, &v.patch} {
		n, err := strconv.Atoi(parts[i])
		if err != nil || n < 0 {
			return semver{}, false
		}
		*dst = n
	}
	return v, true
}

func less(a, b semver) bool {
	if a.major != b.major {
		return a.major < b.major
	}
	if a.minor != b.minor {
		return a.minor < b.minor
	}
	return a.patch < b.patch
}

func formatSemver(v semver) string {
	return "v" + strconv.Itoa(v.major) + "." + strconv.Itoa(v.minor) + "." + strconv.Itoa(v.patch)
}
