package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/xll-gen/xll-gen/internal/config"
	"github.com/xll-gen/xll-gen/internal/ribbon"
	"github.com/xll-gen/xll-gen/internal/versions"
	"github.com/xll-gen/xll-gen/version"
)

// generateRibbonHeaders writes ribbon_xml.h (embedded customUI XML) and
// ribbon_images.h (embedded image bytes + lookup table) for ribbon-enabled
// projects. ribbon_images.h is emitted even with zero file images so the
// template's #include is unconditional.
func generateRibbonHeaders(cfg *config.Config, dir string, baseDir string) error {
	if !cfg.Ribbon.Enabled() {
		return nil
	}
	var xmlStr string
	var imgs []ribbon.Image
	var err error
	if cfg.Ribbon.XML != "" {
		// Raw mode: no file images in v1 (loadImage is rejected by ValidateRawXML).
		xmlStr, err = ribbon.ValidateRawXML(filepath.Join(baseDir, cfg.Ribbon.XML), cfg.Commands)
	} else {
		var names map[string]string
		imgs, names, err = ribbon.Images(cfg, baseDir)
		if err == nil {
			xmlStr, err = ribbon.GenerateXML(cfg, names)
		}
	}
	if err != nil {
		return err
	}
	lit, err := ribbon.ToCppRawLiteral(xmlStr)
	if err != nil {
		return err
	}
	content := "// Code generated by xll-gen. DO NOT EDIT.\n#pragma once\n" +
		"inline const wchar_t* kXllRibbonXml = " + lit + ";\n"
	if err := os.WriteFile(filepath.Join(dir, "ribbon_xml.h"), []byte(content), 0o644); err != nil {
		return err
	}
	return writeRibbonImagesHeader(imgs, dir)
}

// writeRibbonImagesHeader emits ribbon_images.h: one byte array per
// deduplicated image plus GetXllRibbonImages() returning the name->bytes
// table consumed by xll::ribbon::SetRibbonImages.
func writeRibbonImagesHeader(imgs []ribbon.Image, dir string) error {
	var b strings.Builder
	b.WriteString("// Code generated by xll-gen. DO NOT EDIT.\n#pragma once\n")
	b.WriteString("#include \"com/ribbon_image.h\"\n#include <vector>\n\n")
	for i, img := range imgs {
		fmt.Fprintf(&b, "inline const unsigned char kXllRibbonImg%d[] = {", i)
		for j, by := range img.Data {
			if j%16 == 0 {
				b.WriteString("\n    ")
			}
			fmt.Fprintf(&b, "0x%02X,", by)
		}
		b.WriteString("\n};\n")
	}
	b.WriteString("\ninline std::vector<xll::ribbon::RibbonImage> GetXllRibbonImages() {\n    return {\n")
	for i, img := range imgs {
		fmt.Fprintf(&b, "        { L\"%s\", kXllRibbonImg%d, sizeof(kXllRibbonImg%d) },\n", img.Name, i, i)
	}
	b.WriteString("    };\n}\n")
	return os.WriteFile(filepath.Join(dir, "ribbon_images.h"), []byte(b.String()), 0o644)
}

// generateCppMain generates the main C++ file (xll_main.cpp)
func generateCppMain(cfg *config.Config, dir string, shouldAppendPid bool) error {
	data := struct {
		ProjectName     string
		Functions       []config.Function
		Events          []config.Event
		Server          config.ServerConfig
		Build           config.BuildConfig
		ShouldAppendPid bool
		Version         string
		Logging         config.LoggingConfig
		Cache           config.CacheConfig
		Rtd             config.RtdConfig
		Ribbon          config.RibbonConfig
		Commands        []config.Command
	}{
		ProjectName:     cfg.Project.Name,
		Functions:       cfg.Functions,
		Events:          cfg.Events,
		Server:          cfg.Server,
		Build:           cfg.Build,
		ShouldAppendPid: shouldAppendPid,
		Version:         version.Version,
		Logging:         cfg.Logging,
		Cache:           cfg.Cache,
		Rtd:             cfg.Rtd,
		Ribbon:          cfg.Ribbon,
		Commands:        cfg.Commands,
	}

	return executeTemplate("xll_main.cpp.tmpl", filepath.Join(dir, "xll_main.cpp"), data, GetCommonFuncMap())
}

// generateCMake generates the CMakeLists.txt file.
func generateCMake(cfg *config.Config, dir string) error {
	data := struct {
		ProjectName string
		Build       config.BuildConfig
		Version     string
		Rtd         config.RtdConfig
		Ribbon      config.RibbonConfig
		Commands    []config.Command
		Deps        struct {
			FlatBuffers string
			SHM         string
			Types       string
			PHMAP       string
			Zstd        string
		}
	}{
		ProjectName: cfg.Project.Name,
		Build:       cfg.Build,
		Version:     version.Version,
		Rtd:         cfg.Rtd,
		Ribbon:      cfg.Ribbon,
		Commands:    cfg.Commands,
		Deps: struct {
			FlatBuffers string
			SHM         string
			Types       string
			PHMAP       string
			Zstd        string
		}{
			FlatBuffers: versions.FlatBuffers,
			SHM:         versions.SHM,
			Types:       versions.Types,
			PHMAP:       versions.PHMAP,
			Zstd:        versions.Zstd,
		},
	}

	return executeTemplate("CMakeLists.txt.tmpl", filepath.Join(dir, "CMakeLists.txt"), data, nil)
}
