package generator

import (
	"os"
	"path/filepath"

	"github.com/xll-gen/xll-gen/internal/config"
	"github.com/xll-gen/xll-gen/internal/ribbon"
	"github.com/xll-gen/xll-gen/internal/versions"
	"github.com/xll-gen/xll-gen/version"
)

// generateRibbonXmlHeader writes the embedded customUI XML for ribbon-enabled
// projects. Structured mode generates the XML; raw mode validates the user's
// file against the declared commands and embeds it verbatim.
func generateRibbonXmlHeader(cfg *config.Config, dir string, baseDir string) error {
	if !cfg.Ribbon.Enabled() {
		return nil
	}
	var xmlStr string
	var err error
	if cfg.Ribbon.XML != "" {
		xmlStr, err = ribbon.ValidateRawXML(filepath.Join(baseDir, cfg.Ribbon.XML), cfg.Commands)
	} else {
		xmlStr, err = ribbon.GenerateXML(cfg, nil)
	}
	if err != nil {
		return err
	}
	lit, err := ribbon.ToCppRawLiteral(xmlStr)
	if err != nil {
		return err
	}
	content := "// Code generated by xll-gen. DO NOT EDIT.\n#pragma once\n" +
		"inline const wchar_t* kXllRibbonXml = " + lit + ";\n"
	return os.WriteFile(filepath.Join(dir, "ribbon_xml.h"), []byte(content), 0o644)
}

// generateCppMain generates the main C++ file (xll_main.cpp)
func generateCppMain(cfg *config.Config, dir string, shouldAppendPid bool) error {
	data := struct {
		ProjectName     string
		Functions       []config.Function
		Events          []config.Event
		Server          config.ServerConfig
		Build           config.BuildConfig
		ShouldAppendPid bool
		Version         string
		Logging         config.LoggingConfig
		Cache           config.CacheConfig
		Rtd             config.RtdConfig
		Ribbon          config.RibbonConfig
		Commands        []config.Command
	}{
		ProjectName:     cfg.Project.Name,
		Functions:       cfg.Functions,
		Events:          cfg.Events,
		Server:          cfg.Server,
		Build:           cfg.Build,
		ShouldAppendPid: shouldAppendPid,
		Version:         version.Version,
		Logging:         cfg.Logging,
		Cache:           cfg.Cache,
		Rtd:             cfg.Rtd,
		Ribbon:          cfg.Ribbon,
		Commands:        cfg.Commands,
	}

	return executeTemplate("xll_main.cpp.tmpl", filepath.Join(dir, "xll_main.cpp"), data, GetCommonFuncMap())
}

// generateCMake generates the CMakeLists.txt file.
func generateCMake(cfg *config.Config, dir string) error {
	data := struct {
		ProjectName string
		Build       config.BuildConfig
		Version     string
		Rtd         config.RtdConfig
		Ribbon      config.RibbonConfig
		Commands    []config.Command
		Deps        struct {
			FlatBuffers string
			SHM         string
			Types       string
			PHMAP       string
			Zstd        string
		}
	}{
		ProjectName: cfg.Project.Name,
		Build:       cfg.Build,
		Version:     version.Version,
		Rtd:         cfg.Rtd,
		Ribbon:      cfg.Ribbon,
		Commands:    cfg.Commands,
		Deps: struct {
			FlatBuffers string
			SHM         string
			Types       string
			PHMAP       string
			Zstd        string
		}{
			FlatBuffers: versions.FlatBuffers,
			SHM:         versions.SHM,
			Types:       versions.Types,
			PHMAP:       versions.PHMAP,
			Zstd:        versions.Zstd,
		},
	}

	return executeTemplate("CMakeLists.txt.tmpl", filepath.Join(dir, "CMakeLists.txt"), data, nil)
}
