package generator

// Golden-file snapshot suite — the safety net that precedes the R22 marshalling
// ladder refactor. It captures the CURRENT codegen output of the three
// template-driven artifacts (xll_main.cpp, server.go, interface.go) byte-for-
// byte so a later "output-neutral" refactor can be proven neutral: if a golden
// drifts, this test fails and prints the first differing byte.
//
// This file adds tests + testdata ONLY. It does not (and must not) touch any
// template under internal/templates/*.tmpl or any generator logic — it captures
// whatever those currently produce.
//
// Determinism contract (see the package report / AGENTS.md for the rationale):
//   - Version is injected as the constant "golden" via the render data, never
//     read from version.Version. The render path here (renderTemplate) is the
//     SAME templates.Get + template.New(name).Funcs(GetCommonFuncMap()).Parse +
//     Execute pipeline executeTemplate uses, so the captured bytes equal what
//     the real generator writes, modulo the version string we pin.
//   - Module path / package name are pinned constants.
//   - All template iteration is over ordered slices (Functions/Args/Events/
//     Commands); there is no Go-map ranging in the templates, so iteration order
//     is stable.
//   - The pipeline does NOT run gofmt on generated Go (executeTemplate writes
//     raw template output); the goldens are therefore the raw template bytes,
//     exactly as shipped. We still assertParses the Go before snapshotting so a
//     syntactically broken render is never frozen into a golden.

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/xll-gen/xll-gen/internal/config"
)

// goldenVersion is the pinned version string injected into every render so the
// "Code generated by xll-gen <ver>." banner never leaks version.Version.
const goldenVersion = "golden"

const (
	goldenPackage = "generated"
	goldenModName = "goldenmod"
	goldenProject = "GoldenProj"
)

// goldenConfig builds the single fixture that drives every per-type marshalling
// branch of the ladder. It is normalized via config.ApplyDefaults and checked
// with config.Validate so the captured output matches the real generation path
// (rejected combinations — e.g. range/grid returns, nullable scalar args — are
// intentionally absent; see the report).
//
// Ladder-site coverage (arg type x return type x mode x variant). Each fixture
// function is annotated with the site(s) it exercises.
func goldenConfig() *config.Config {
	cfg := &config.Config{
		Project: config.ProjectConfig{Name: goldenProject, Version: "0.1.0"},
		Build: config.BuildConfig{
			Singlefile: "xll",
			TempDir:    "temp_golden",
		},
		Logging: config.LoggingConfig{Level: "info", Dir: "logs"},
		Cache:   config.CacheConfig{Enabled: true, TTL: "10m"},
		Server: config.ServerConfig{
			Timeout: "2s",
			Workers: 4,
			Launch:  &config.LaunchConfig{Enabled: boolPtr(true)},
		},
		Rtd: config.RtdConfig{
			Enabled:     true,
			ProgID:      goldenProject + ".Rtd",
			Clsid:       "{11111111-2222-3333-4444-555555555555}",
			Description: "Golden RTD",
		},
		Functions: []config.Function{
			// ---- SYNC: each scalar/composite type arg -> matching return ----
			// Sites: sync string arg + string return.
			{Name: "SyncStr", Mode: "sync", Return: "string",
				Args: []config.Arg{{Name: "s", Type: "string"}}},
			// Sites: sync int arg + int return.
			{Name: "SyncInt", Mode: "sync", Return: "int",
				Args: []config.Arg{{Name: "i", Type: "int"}}},
			// Sites: sync float arg + float return.
			{Name: "SyncFloat", Mode: "sync", Return: "float",
				Args: []config.Arg{{Name: "f", Type: "float"}}},
			// Sites: sync bool arg + bool return.
			{Name: "SyncBool", Mode: "sync", Return: "bool",
				Args: []config.Arg{{Name: "b", Type: "bool"}}},
			// Sites: sync any arg + any return.
			{Name: "SyncAny", Mode: "sync", Return: "any",
				Args: []config.Arg{{Name: "a", Type: "any"}}},
			// Sites: sync grid arg + grid return (composite serialize+spill).
			{Name: "SyncGrid", Mode: "sync", Return: "grid",
				Args: []config.Arg{{Name: "g", Type: "grid"}}},
			// Sites: sync numgrid arg + numgrid return (FP12 serialize+spill).
			{Name: "SyncNumGrid", Mode: "sync", Return: "numgrid",
				Args: []config.Arg{{Name: "ng", Type: "numgrid"}}},
			// Sites: sync range arg (range is arg-only; return int).
			{Name: "SyncRange", Mode: "sync", Return: "int",
				Args: []config.Arg{{Name: "r", Type: "range"}}},
			// Sites: sync date arg (date is arg-only via the double path; return int).
			{Name: "SyncDate", Mode: "sync", Return: "int",
				Args: []config.Arg{{Name: "d", Type: "date"}}},
			// Sites: sync multi-arg (string,int,float,bool,grid) covering the
			// per-arg decode ladder in one wrapper.
			{Name: "SyncMulti", Mode: "sync", Return: "string",
				Args: []config.Arg{
					{Name: "s", Type: "string"},
					{Name: "i", Type: "int"},
					{Name: "f", Type: "float"},
					{Name: "b", Type: "bool"},
					{Name: "g", Type: "grid"},
				}},
			// Sites: sync + per-function cache.enabled (cache-hit path) grid return.
			{Name: "SyncCachedGrid", Mode: "sync", Return: "grid",
				Cache: &config.FunctionCacheConfig{Enabled: boolPtr(true), TTL: "1m"},
				Args:  []config.Arg{{Name: "k", Type: "string"}}},
			// Sites: caller+macro with a range arg (xlfCaller + xlfGetCell path).
			{Name: "CallerMacroRange", Mode: "sync", Return: "int",
				Caller: true, Macro: true,
				Args: []config.Arg{{Name: "r", Type: "range"}}},

			// ---- ASYNC: scalar + composite + any returns ----
			// Sites: async string return.
			{Name: "AsyncStr", Mode: "async", Return: "string",
				Args: []config.Arg{{Name: "s", Type: "string"}}},
			// Sites: async int return.
			{Name: "AsyncInt", Mode: "async", Return: "int",
				Args: []config.Arg{{Name: "i", Type: "int"}}},
			// Sites: async grid return (validate + queue under composite tag).
			{Name: "AsyncGrid", Mode: "async", Return: "grid",
				Args: []config.Arg{{Name: "g", Type: "grid"}}},
			// Sites: async numgrid return.
			{Name: "AsyncNumGrid", Mode: "async", Return: "numgrid",
				Args: []config.Arg{{Name: "ng", Type: "numgrid"}}},
			// Sites: async any return.
			{Name: "AsyncAny", Mode: "async", Return: "any",
				Args: []config.Arg{{Name: "a", Type: "any"}}},

			// ---- RTD (streaming): scalar args, composite args, range+any ----
			// Sites: rtd scalar args (int,string,float) -> any push.
			{Name: "RtdScalars", Mode: "rtd", Return: "any",
				Args: []config.Arg{
					{Name: "i", Type: "int"},
					{Name: "s", Type: "string"},
					{Name: "f", Type: "float"},
				}},
			// Sites: rtd composite args (grid,numgrid) via content-hash payload path.
			{Name: "RtdComposite", Mode: "rtd", Return: "any",
				Args: []config.Arg{
					{Name: "g", Type: "grid"},
					{Name: "ng", Type: "numgrid"},
				}},
			// Sites: rtd range + any args.
			{Name: "RtdRangeAny", Mode: "rtd", Return: "any",
				Args: []config.Arg{
					{Name: "r", Type: "range"},
					{Name: "a", Type: "any"},
				}},

			// ---- RTD-ONCE: scalar/grid/numgrid returns, composite args, memoize ----
			// Sites: rtd-once scalar return (miss -> VARIANT sentinel).
			{Name: "OnceScalar", Mode: "rtd-once", Return: "float",
				Args: []config.Arg{{Name: "i", Type: "int"}, {Name: "f", Type: "float"}}},
			// Sites: rtd-once grid return (spill via RtdOnceGridRegistry).
			{Name: "OnceGrid", Mode: "rtd-once", Return: "grid",
				Args: []config.Arg{{Name: "s", Type: "string"}}},
			// Sites: rtd-once numgrid return (FP12 spill).
			{Name: "OnceNumGrid", Mode: "rtd-once", Return: "numgrid",
				Args: []config.Arg{{Name: "s", Type: "string"}}},
			// Sites: rtd-once composite args (grid,numgrid,range,any) — content-hash
			// arg path on the once route.
			{Name: "OnceComposite", Mode: "rtd-once", Return: "any",
				Args: []config.Arg{
					{Name: "g", Type: "grid"},
					{Name: "ng", Type: "numgrid"},
					{Name: "r", Type: "range"},
					{Name: "a", Type: "any"},
				}},
			// Sites: rtd-once + memoize:true (persist until unload).
			{Name: "OnceMemoize", Mode: "rtd-once", Return: "float", Memoize: true,
				Args: []config.Arg{{Name: "i", Type: "int"}}},
			// Sites: rtd-once + memoize_ttl="5s" (cache-for-TTL middle ground).
			{Name: "OnceTTL", Mode: "rtd-once", Return: "float", MemoizeTTL: "5s",
				Args: []config.Arg{{Name: "i", Type: "int"}}},
		},
		Events: []config.Event{
			// Sites: built-in CalculationEnded event handler.
			{Type: "CalculationEnded", Handler: "OnRecalc"},
		},
		Commands: []config.Command{
			// Sites: command (macroType=2) proc + dispatch.
			{Name: "RunReport", Description: "Runs the report", Handler: "RunReport"},
		},
	}

	// Normalize exactly as the real load path does, then assert the fixture is
	// a legal config (so we never snapshot output the generator would reject).
	config.ApplyDefaults(cfg)
	return cfg
}

func boolPtr(b bool) *bool { return &b }

// renderGolden renders the three template artifacts for the golden fixture with
// the version pinned, mirroring the data structs the generator's generateServer
// / generateInterface / generateCppMain build (but with Version="golden" and
// fixed module/package). Returns a name->bytes map. assertParses is run on the
// Go artifacts before they are returned so a broken render is never captured.
func renderGolden(t *testing.T) map[string][]byte {
	t.Helper()
	cfg := goldenConfig()

	// Belt-and-suspenders: the fixture must be a legal config (real-path parity).
	if err := config.Validate(cfg); err != nil {
		t.Fatalf("golden fixture failed config.Validate (would never reach codegen): %v", err)
	}

	// interface.go — mirrors generateInterface's anonymous struct.
	ifaceData := struct {
		Package   string
		ModName   string
		Functions []config.Function
		Events    []config.Event
		Commands  []config.Command
		Version   string
		Rtd       config.RtdConfig
	}{
		Package:   goldenPackage,
		ModName:   goldenModName,
		Functions: cfg.Functions,
		Events:    cfg.Events,
		Commands:  cfg.Commands,
		Version:   goldenVersion,
		Rtd:       cfg.Rtd,
	}

	// server.go — mirrors generateServer's anonymous struct.
	srvData := struct {
		Package       string
		ModName       string
		ProjectName   string
		Functions     []config.Function
		Events        []config.Event
		Commands      []config.Command
		ServerTimeout string
		ServerWorkers int
		Version       string
		Logging       config.LoggingConfig
		Rtd           config.RtdConfig
		Chunk         *config.ChunkConfig
	}{
		Package:       goldenPackage,
		ModName:       goldenModName,
		ProjectName:   cfg.Project.Name,
		Functions:     cfg.Functions,
		Events:        cfg.Events,
		Commands:      cfg.Commands,
		ServerTimeout: cfg.Server.Timeout,
		ServerWorkers: cfg.Server.Workers,
		Version:       goldenVersion,
		Logging:       cfg.Logging,
		Rtd:           cfg.Rtd,
		Chunk:         cfg.Server.Chunk,
	}

	// xll_main.cpp — mirrors generateCppMain's anonymous struct. ShouldAppendPid
	// is pinned false (a fixed boolean either way; false yields the static-name
	// branch, which is stable).
	cppData := struct {
		ProjectName     string
		Functions       []config.Function
		Events          []config.Event
		Server          config.ServerConfig
		Build           config.BuildConfig
		ShouldAppendPid bool
		Version         string
		Logging         config.LoggingConfig
		Cache           config.CacheConfig
		Rtd             config.RtdConfig
		Ribbon          config.RibbonConfig
		Commands        []config.Command
	}{
		ProjectName:     cfg.Project.Name,
		Functions:       cfg.Functions,
		Events:          cfg.Events,
		Server:          cfg.Server,
		Build:           cfg.Build,
		ShouldAppendPid: false,
		Version:         goldenVersion,
		Logging:         cfg.Logging,
		Cache:           cfg.Cache,
		Rtd:             cfg.Rtd,
		Ribbon:          cfg.Ribbon,
		Commands:        cfg.Commands,
	}

	iface := []byte(renderTemplate(t, "interface.go.tmpl", ifaceData))
	srv := []byte(renderTemplate(t, "server.go.tmpl", srvData))
	cpp := []byte(renderTemplate(t, "xll_main.cpp.tmpl", cppData))

	// Never freeze a syntactically broken Go render into a golden.
	assertParses(t, "interface.go", string(iface))
	assertParses(t, "server.go", string(srv))

	return map[string][]byte{
		"interface.go.golden": iface,
		"server.go.golden":    srv,
		"xll_main.cpp.golden": cpp,
	}
}

// goldenDir is where the snapshot files live.
func goldenDir() string {
	return filepath.Join("testdata", "golden")
}

// firstDiff returns a human-readable description of the first byte/line where
// got and want diverge, for actionable FAIL messages.
func firstDiff(got, want []byte) string {
	n := len(got)
	if len(want) < n {
		n = len(want)
	}
	line, col := 1, 1
	for i := 0; i < n; i++ {
		if got[i] != want[i] {
			return describeDiff(line, col, i, got, want)
		}
		if got[i] == '\n' {
			line++
			col = 1
		} else {
			col++
		}
	}
	if len(got) != len(want) {
		return describeLenDiff(line, col, n, got, want)
	}
	return "no byte difference (lengths equal)"
}

func describeDiff(line, col, i int, got, want []byte) string {
	return formatDiff(line, col, i,
		byteContext(got, i), byteContext(want, i),
		len(got), len(want))
}

func describeLenDiff(line, col, n int, got, want []byte) string {
	which := "got is longer"
	if len(want) > len(got) {
		which = "want is longer"
	}
	return formatDiff(line, col, n,
		byteContext(got, n), byteContext(want, n),
		len(got), len(want)) + " (" + which + ")"
}

func formatDiff(line, col, off int, gotCtx, wantCtx string, gotLen, wantLen int) string {
	return "first diff at line " + itoa(line) + " col " + itoa(col) +
		" (byte offset " + itoa(off) + "); got len=" + itoa(gotLen) +
		" want len=" + itoa(wantLen) + "\n  got : ..." + gotCtx +
		"...\n  want: ..." + wantCtx + "..."
}

// byteContext returns up to 40 bytes of context centered on offset i.
func byteContext(b []byte, i int) string {
	start := i - 20
	if start < 0 {
		start = 0
	}
	end := i + 20
	if end > len(b) {
		end = len(b)
	}
	return string(b[start:end])
}

// itoa avoids pulling strconv into the diff path for one small need.
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}

// TestGolden is the snapshot safety net. With UPDATE_GOLDEN=1 it (re)writes the
// goldens; otherwise it compares the freshly rendered artifacts to the snapshots
// byte-for-byte. It also self-checks render determinism by rendering twice.
func TestGolden(t *testing.T) {
	// Self-flake guard: two independent renders must be byte-identical. If this
	// fails the fixture/templates leak nondeterminism (version, ordering, paths)
	// and the goldens would be meaningless.
	first := renderGolden(t)
	second := renderGolden(t)
	for name, a := range first {
		b := second[name]
		if !bytes.Equal(a, b) {
			t.Fatalf("nondeterministic render for %s: two renders differ:\n%s", name, firstDiff(a, b))
		}
	}

	dir := goldenDir()
	update := os.Getenv("UPDATE_GOLDEN") == "1"

	if update {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			t.Fatal(err)
		}
		for name, content := range first {
			path := filepath.Join(dir, name)
			if err := os.WriteFile(path, content, 0o644); err != nil {
				t.Fatalf("write golden %s: %v", path, err)
			}
			t.Logf("wrote golden %s (%d bytes, %d lines)", path, len(content), bytes.Count(content, []byte{'\n'})+1)
		}
		return
	}

	for name, got := range first {
		path := filepath.Join(dir, name)
		want, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read golden %s: %v\n(run UPDATE_GOLDEN=1 go test ./internal/generator/ -run TestGolden to (re)create)", path, err)
		}
		if !bytes.Equal(got, want) {
			t.Errorf("golden mismatch for %s:\n%s\n(if this change is intentional, re-run with UPDATE_GOLDEN=1)", name, firstDiff(got, want))
		}
	}
}
